# db.classname=com.mysql.jdbc.Driver
# db.url=jdbc:mysql://localhost:3306/PanyaPanya
# db.username=root
# db.password=1111

# db.classname=com.mysql.cj.jdbc.Driver
# db.url=jdbc:mysql://mysql.railway.internal:3306/railway?serverTimezone=UTC&useSSL=false
# db.username=root
# db.password=fWDqgZdXCffprERDkpdypBySjzzxTkbl

db.classname=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://containers-us-west-1.railway.app:3306/railway?serverTimezone=UTC&useSSL=false
db.username=root
db.password=fWDqgZdXCffprERDkpdypBySjzzxTkbl