# db.classname=com.mysql.jdbc.Driver
# db.url=jdbc:mysql://localhost:3306/PanyaPanya
# db.username=root
# db.password=1111

# db.classname=com.mysql.cj.jdbc.Driver
# db.url=jdbc:mysql://crossover.proxy.rlwy.net:31035/railway?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
# db.username=root
# db.password=vSOQwXsvCdLrcYFzwUvADIeBFkHRhnjx

db.classname=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-61fd2b1-nate-54f9.e.aivencloud.com:27340/defaultdb?sslMode=REQUIRED&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
db.username=avnadmin
db.password=AVNS_BDYVxjo9kibJwY-eDY7